SET FOREIGN_KEY_CHECKS = 0;

-- ## --
DROP TABLE IF EXISTS Application;
DROP TABLE IF EXISTS LogPoint;
DROP TABLE IF EXISTS ProbeTag;
DROP TABLE IF EXISTS ReferenceEvent;
DROP TABLE IF EXISTS TracePoint;
DROP TABLE IF EXISTS Webhook;
-- ## --

SET FOREIGN_KEY_CHECKS = 1;


