SET FOREIGN_KEY_CHECKS = 0;

-- ## --
TRUNCATE TABLE Application;
TRUNCATE TABLE ApplicationConfig;
TRUNCATE TABLE LogPoint;
TRUNCATE TABLE ReferenceEvent;
TRUNCATE TABLE ServerStatistics;
TRUNCATE TABLE TracePoint;
TRUNCATE TABLE Webhook;
-- ## --

SET FOREIGN_KEY_CHECKS = 1;

