name: release-internal-repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure CI Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Configure Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: >-
            [
              {
                "id": "sidekick-oss-releases",
                "url": "https://repo.thundra.io/content/repositories/sidekick-oss-releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "sidekick-oss-snapshots",
                "url": "https://repo.thundra.io/content/repositories/sidekick-oss-snapshots",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >-
            [
              {
                "id": "sidekick-oss-releases",
                "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME  }}",
                "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD  }}"
              },
              {
                "id": "sidekick-oss-snapshots",
                "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME  }}",
                "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD  }}"
              }
            ]

      - name: Build and Release Snapshot with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
        run: mvn -q clean install deploy --batch-mode -P release
